version: '3.8'
services:
  app:
    build: ./app
    command: sleep infinity
    volumes:
      - ./app:/app
    environment:
      - HELIUM_DATABASE_URL=postgres://dbuser:dbpwd@localhost:5432/appdb
    network_mode: host
  database:
    image: postgres:15.2
    ports:
    - "5432:5432"
    volumes:
      - /data/HasuraStarterKit/database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: appdb
    network_mode: host
  hasura:
    image: hasura/graphql-engine:v2.23.0
    ports:
    - "8080:8080"
    depends_on:
    - "database"
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://dbuser:dbpwd@localhost:5432/appdb
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    network_mode: host